"""Generate SocioSim v4 direct-use synthetic decorative assets.

The generated images are project-owned abstract artwork. They intentionally
contain no people, brands, dashboard KPIs, screenshots, testimonials, or claims.
"""

from __future__ import annotations

import hashlib
import json
import math
import struct
import zlib
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "socio_sim" / "web" / "static" / "assets" / "v4"


def _png(rgb: np.ndarray) -> bytes:
    h, w, _ = rgb.shape
    raw = bytearray()
    row = rgb.reshape(h, w * 3)
    for y in range(h):
        raw.append(0)
        raw.extend(row[y].tobytes())
    comp = zlib.compress(bytes(raw), 9)

    def chunk(typ: bytes, data: bytes) -> bytes:
        body = typ + data
        return (struct.pack(">I", len(data)) + body
                + struct.pack(">I", zlib.crc32(body) & 0xFFFFFFFF))

    ihdr = struct.pack(">IIBBBBB", w, h, 8, 2, 0, 0, 0)
    return b"\x89PNG\r\n\x1a\n" + chunk(b"IHDR", ihdr) + chunk(b"IDAT", comp) + chunk(b"IEND", b"")


def _art(seed: int, w: int, h: int, role: str) -> np.ndarray:
    rng = np.random.default_rng(seed)
    yy, xx = np.mgrid[0:h, 0:w].astype(float)
    nx = xx / max(w - 1, 1)
    ny = yy / max(h - 1, 1)
    palette = np.array([
        [31, 78, 121], [220, 92, 70], [242, 177, 84], [61, 148, 126],
        [88, 91, 160], [235, 235, 226], [44, 47, 51], [173, 211, 196],
    ], dtype=float)
    c1, c2, c3 = palette[rng.choice(len(palette), 3, replace=False)]
    field = (c1 * (1 - nx[..., None]) + c2 * nx[..., None]) * 0.58
    field += c3 * (0.42 * (1 - ny[..., None]))
    for i in range(5 + seed % 5):
        cx = rng.uniform(0.05, 0.95) * w
        cy = rng.uniform(0.05, 0.95) * h
        rx = rng.uniform(0.08, 0.28) * w
        ry = rng.uniform(0.08, 0.30) * h
        angle = rng.uniform(0, math.pi)
        ca, sa = math.cos(angle), math.sin(angle)
        dx = xx - cx
        dy = yy - cy
        ex = (dx * ca + dy * sa) / rx
        ey = (-dx * sa + dy * ca) / ry
        mask = np.clip(1 - (ex * ex + ey * ey), 0, 1)[..., None]
        color = palette[int(rng.integers(0, len(palette)))]
        field = field * (1 - 0.55 * mask) + color * (0.55 * mask)
    if role == "ad_creative":
        band = (np.sin((nx * (4 + seed % 4) + ny * 1.7) * math.pi) > 0.25)[..., None]
        field = np.where(band, field * 0.82 + np.array([245, 245, 238]) * 0.18, field)
    elif role == "editorial":
        ring = np.abs(np.sqrt((nx - 0.5) ** 2 + (ny - 0.48) ** 2) - 0.26)
        field = np.where((ring < 0.018)[..., None], field * 0.4 + c1 * 0.6, field)
    noise = rng.normal(0, 4, size=field.shape)
    return np.clip(field + noise, 0, 255).astype(np.uint8)


def _phash(rgb: np.ndarray) -> str:
    small = rgb[:: max(rgb.shape[0] // 16, 1), :: max(rgb.shape[1] // 16, 1), :][:16, :16]
    gray = small.mean(axis=2)
    bits = gray > gray.mean()
    value = 0
    for bit in bits.flatten():
        value = (value << 1) | int(bit)
    return f"{value:064x}"


def _write(role: str, prefix: str, count: int, w: int, h: int, aspect: str, start_seed: int):
    rows = []
    for i in range(count):
        asset_id = f"{prefix}-{i:02d}"
        name = f"{asset_id}.png"
        rgb = _art(start_seed + i, w, h, role)
        data = _png(rgb)
        path = OUT / name
        path.write_bytes(data)
        rows.append({
            "asset_id": asset_id,
            "file_path": f"socio_sim/web/static/assets/v4/{name}",
            "role": role,
            "aspect_ratio": aspect,
            "intrinsic_width": w,
            "intrinsic_height": h,
            "source_type": "synthetic_decorative_artwork",
            "license": "MIT project-owned",
            "provenance": "generated by scripts/generate_v4_assets.py; no real people, brands, screenshots, or KPIs",
            "content_risk_tags": ["decorative", "non_documentary", "no_people", "no_brands"],
            "accessibility_alt_template": (
                "Synthetic decorative artwork for a SocioSim {role}; not evidence."),
            "sha256": hashlib.sha256(data).hexdigest(),
            "perceptual_hash": _phash(rgb),
            "approval_status": "qa_pending",
        })
    return rows


def main() -> int:
    OUT.mkdir(parents=True, exist_ok=True)
    for old in OUT.glob("*.png"):
        old.unlink()
    records = []
    records += _write("feed_cover", "feed-cover-v4", 48, 1200, 800, "3:2", 1100)
    records += _write("ad_creative", "ad-creative-v4", 32, 1200, 600, "2:1", 2100)
    records += _write("editorial_system", "editorial-v4", 12, 1600, 900, "16:9", 3100)
    registry = {
        "schema_version": 1,
        "generated_by": "scripts/generate_v4_assets.py",
        "human_review": {
            "status": "not_reviewed",
            "reviewer": "",
            "date": "",
            "scope": "",
            "defects_found": [],
        },
        "assets": records,
    }
    (OUT / "registry.json").write_text(json.dumps(registry, indent=2, sort_keys=True),
                                       encoding="utf-8")
    print(f"generated {len(records)} v4 assets in {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
