# Fable Forensic Audit Runner
# Collects source files -> calls claude-fable-5 subprocess -> writes audit output
# Does NOT analyze code itself. All analysis is Fable's.

$ErrorActionPreference = "Stop"
$RepoRoot = "C:\Users\jviol\Downloads\socio_sim"
$ClaudeExe = "C:\Users\jviol\.local\bin\claude.exe"
$OutDir = Join-Path $RepoRoot "docs\audits"
$Timestamp = Get-Date -Format "yyyyMMdd_HHmm"
$AuditFile = Join-Path $OutDir "fable_audit_$Timestamp.md"

if (-not (Test-Path $OutDir)) { New-Item -ItemType Directory -Path $OutDir -Force | Out-Null }

Write-Host "[1/4] Collecting source files..."

$FilesToRead = @(
    "socio_sim\content\llm_adapter.py",
    "socio_sim\content\llm_cache.py",
    "socio_sim\content\claude_adapter.py",
    "socio_sim\web\app.py",
    "socio_sim\core\__init__.py",
    "tests\test_llm_adapter.py",
    "tests\test_web.py",
    "scripts\claim_scan.py",
    "scripts\evidence_gate.py",
    "pyproject.toml",
    "run.py"
)

$Codebase = ""
foreach ($f in $FilesToRead) {
    $full = Join-Path $RepoRoot $f
    if (Test-Path $full) {
        $Codebase += "`n=== FILE: $f ===`n"
        $Codebase += (Get-Content $full -Raw -ErrorAction SilentlyContinue)
        Write-Host "  read: $f"
    } else {
        Write-Host "  skip (not found): $f"
    }
}

Write-Host "[2/4] Building Fable audit prompt (codebase: $($Codebase.Length) chars)..."

$AuditPrompt = @"
You are claude-fable-5 performing a forensic audit of the socio_sim research simulator codebase.

[CODEBASE]
$Codebase
[/CODEBASE]

Audit ALL 8 areas below. Use ONLY this output format for every finding:

FINDING [ID] | SEVERITY: P0/P1/P2/P3 | FILE: path:linenum
ISSUE: exact description of the problem
EVIDENCE: exact code snippet (2-5 lines)
FIX: before -> after (minimal targeted change only)
TEST: test name or assertion to verify

AUDIT AREAS:
A - Data lineage: every hardcoded number must be labeled measured/external_aggregate/scenario_assumption/synthetic_engineering/user_supplied/unsupported. Flag any unlabeled numeric constants that could be mistaken for empirical data.
B - Model validity: classifier names, benchmark claims, accuracy claims, misleading aliases. Any claim that a model "achieves X%" or "outperforms Y" without a cited source.
C - Calibration claims: any use of calibrated/validated/backtest/confidence interval/significance/causal language without experimental backing.
D - Causal marketing: lift/ROAS/iROAS/CAC/LTV/attribution/holdout/CUPED language without proper experimental design (RCT or DiD with holdout).
E - LLM safety and cache: (1) blocked LLM responses must never be served from cache (2) provenance tags on all LLM output (3) SSRF risks in any URL construction (4) prompt injection surfaces (5) tamper detection on cache entries.
F - Security: unauthenticated API routes, secrets in code or config, host-header injection, path traversal, dependency CVEs, publicly-exposed endpoints.
G - Accessibility: WCAG 2.2 AA compliance - keyboard navigation, focus management, ARIA labels, color contrast, alt text on all images.
H - Assets: static file integrity, orphaned files, legacy v3 assets, missing or broken references.

After all findings, output:
---
VERDICT: [FAIL / CONDITIONAL PASS / PASS FOR LOCAL RESEARCH USE ONLY / PASS FOR ENTERPRISE]
REASON: [one sentence]
---
TOP 5 PRIORITY FIXES (by risk):
1. [ID] - [description]
2. [ID] - [description]
3. [ID] - [description]
4. [ID] - [description]
5. [ID] - [description]
"@

Write-Host "[3/4] Calling Fable subprocess (this may take several minutes)..."

$FableOutput = $AuditPrompt | & $ClaudeExe --model claude-fable-5 -p 2>&1

Write-Host "[3/4] Fable returned $($FableOutput.Length) chars"

Write-Host "[4/4] Writing audit output..."
$Header = @"
# Fable Forensic Audit - $Timestamp
Generated by: claude-fable-5 via subprocess
Runner: scripts/run_fable_audit.ps1
Branch: $(git -C $RepoRoot rev-parse --abbrev-ref HEAD 2>&1)
Commit: $(git -C $RepoRoot rev-parse --short HEAD 2>&1)

---

"@

($Header + ($FableOutput -join "`n")) | Out-File -FilePath $AuditFile -Encoding utf8

Write-Host "Audit written to: $AuditFile"
Write-Host "Done."
